### ISSUE TITLE
"use HyperMock" implicitly defines a function in my modules

### ISSUE THREAD

**Issue by josevalim** [stevegraham/hypermock#1]
There is no need for HyperMock to inject functions in the user scope. Likely, there is even no need for `use HyperMock` at all. Here is what I would do:
1. Make the adapter a configuration option
2. Provide an application endpoint (the one you get when you do `mix new my_app --sup`) that will read the configuration with `Application.get_env(:hypermock, :adapter)` and start it accordingly

This way, folks can either do `import HyperMock` or `require HyperMock`, without a need for using or injecting code.

**Comment by stevegraham** [comment]
If I remove https://github.com/stevegraham/hypermock/blob/a046ac1ec4fe6a4f563ade33f284b42bfaf8d9f1/lib/hypermock.ex#L6 and make `adapter` a compile time attribute the problem goes away, correct?

I copied the `use` pattern from exvcr. The main objection here is implicit function definition in the user scope. Granted that `intercept/1` imports functions in the function scope, but I don't find this surprising for the user as they explicitly have to call `intercept/1` for that to happen. I don't think I'm going to make adapter a configuration option, it seems OTT to me. _however_ I am in no doubt that you have much more insight into this than I, if there is something glaring I am overlooking here please tell me.

Thanks for the first issue! (and of course Elixir itself 😊) <3

**Comment by josevalim** [comment]
It is ok for you to import when you do `use`. My biggest annoyance was just defining the function explicitly, so the module attribute improves things. I would be nice to get rid of `use` too because you could just check for `@adapter` being nil and act accordingly. You should not need to start the adapter code because the user needs to start in their own application tree, otherwise their app won't even work.
